# Site settings
title: pdp elements
email: go4cas@gmail.com
description: a set of web-components used to build an e-commerce product detail page
footer_text: 'eCommerce from the eyes of <a href="https://github.com/go4cas">Cas</a>. Template awesome sauce by <a href="http://github.com/raichur/material-jekyll">Joshua Raichur</a>. Hosted at <a href="js.org"><img src="http://logo.js.org/bright_tiny.png" width="40" alt="JS.ORG Logo"/></a>.'
baseurl: ""

# Social usernames
twitter_username: go4cas
github_username:  go4cas
email: g04cas@gmail.com

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
