# Site settings
title: pdp elements
email: go4cas@gmail.com
description: a set of web-components used to build an e-commerce product detail page
footer_text: 'Made with <span class="icon-favorite pulse"></span> by <a href="http://joshuaraichur.com">Joshua Raichur</a>. <a href="http://github.com/raichur/material-jekyll">Fork the source.</a>'
baseurl: ""

# Social usernames
twitter_username: go4cas
github_username:  go4cas
email: g04cas@gmail.com

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
