# Site settings
title: pdp elements
email: go4cas@gmail.com
description: a series of articles for building the uber product detail page
footer_text: 'Template awesomeness by <a href="http://github.com/raichur/material-jekyll">Joshua Raichur</a><br>Hosted at <a href="https://js.org"><img src="http://logo.js.org/bright_tiny.png" width="40" alt="JS.ORG Logo"/></a>'
baseurl: ""

# Social usernames
twitter_username: go4cas
github_username:  go4cas
email: go4cas@gmail.com

# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
